### ISSUE TITLE
The container is started but the DNS server does not work

### ISSUE THREAD

**Issue by mengqiang81** [spops/docker-dnsmasq#1]
Hi, i followed your guides. 
The output looks like this
````
dnsmasq: started, version 2.68 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 10.237.148.60#53
dnsmasq: using nameserver 10.237.148.54#53
dnsmasq: using nameserver 10.236.158.106#53
dnsmasq: read /etc/banner_add_hosts - 2 addresses
````
when I am using `docker logs`.
So i think the container is started with no problem. 

But i find my domain name is resoluted by another DNS server when i am using `nslookup`
I `telnet` the 53 port and it is ok. 
I get inside my container and `ping` my host ip address and it is ok. 

So what is wrong, i need your help.

Thanks

**Comment by jiasir** [comment]
This is about udp 53 port of DNS not exposed. We have fixed it. Many thanks.
